export interface PatientFieldConfig {
    id: string;      // e.g. 'name', 'age', 'sex', 'address', 'regNo', 'date', 'weight', 'phone'
    label: string;
    visible: boolean;
    order: number;
}

export interface BodySectionConfig {
    id: string;
    label: string;
    visible: boolean;
    order: number;
    placeholder?: string;
}

export interface PrescriptionHeaderConfig {
    doctorName: string;
    showDoctorName: boolean;
    degrees: string;
    showDegrees: boolean;
    specialties: string[];
    showSpecialties: boolean;
    department: string;
    showDepartment: boolean;
    institute: string;
    showInstitute: boolean;
    regNo: string;
    showRegNo: boolean;

    chamberName: string;
    showChamberName: boolean;
    chamberAddress: string;
    showChamberAddress: boolean;
    mobile: string;
    showMobile: boolean;
    visitTime: string;
    showVisitTime: boolean;
    offDay: string;
    showOffDay: boolean;


    leftSideBgColor: string;
    rightSideBgColor: string;
    textColor: string;

    patientFields: PatientFieldConfig[];
}

export interface PrescriptionBodyConfig {
    labelRx: string;        // default: Rx.
    sections: BodySectionConfig[];

    // Layout
    showLeftColumn: boolean; // Toggle entire left column
    showBarcode: boolean;
}

export interface PrescriptionFooterConfig {
    disclaimerText: string;
    showCredits: boolean;
    creditsText: string;

    // Design
    backgroundColor: string;
    textColor: string;
}

export const DEFAULT_HEADER_CONFIG: PrescriptionHeaderConfig = {
    doctorName: 'Munshi Faysal',
    showDoctorName: true,
    degrees: 'MBBS, MD',
    showDegrees: true,
    specialties: ['Medicine Specialist'],
    showSpecialties: true,
    department: 'Department Of Medicine',
    showDepartment: true,
    institute: 'Demo Medical College',
    showInstitute: true,
    regNo: '112589',
    showRegNo: true,
    chamberName: 'Crescent Diagnostic Center',
    showChamberName: true,
    chamberAddress: 'Panthapath, Dhaka',
    showChamberAddress: true,
    mobile: '01617425842',
    showMobile: true,
    visitTime: '4PM-10PM',
    showVisitTime: true,
    offDay: 'Friday Off',
    showOffDay: true,
    leftSideBgColor: '#f3f4f6',
    rightSideBgColor: '#f3f4f6',
    textColor: '#1f2937',

    patientFields: [
        { id: 'name', label: 'Name', visible: true, order: 1 },
        { id: 'age', label: 'Age', visible: true, order: 2 },
        { id: 'sex', label: 'Sex', visible: true, order: 3 },
        { id: 'address', label: 'Address', visible: true, order: 4 },
        { id: 'regNo', label: 'Reg. No', visible: true, order: 5 },
        { id: 'date', label: 'Date', visible: true, order: 6 },
        { id: 'weight', label: 'Wt', visible: true, order: 7 },
        { id: 'phone', label: 'Mobile', visible: true, order: 8 }
    ]
};

export const DEFAULT_BODY_CONFIG: PrescriptionBodyConfig = {
    labelRx: 'Rx.',
    showLeftColumn: true,
    showBarcode: true,
    sections: [
        { id: 'disease', label: 'Dx', visible: true, order: 0, placeholder: 'Type content...' },
        { id: 'cc', label: 'C/C', visible: true, order: 1, placeholder: 'Type content...' },
        { id: 'oe', label: 'O/E', visible: true, order: 2, placeholder: 'Type content...' },
        { id: 'ix', label: 'I/X', visible: true, order: 3, placeholder: 'Type content...' },
        { id: 'advice', label: 'Advice', visible: true, order: 4, placeholder: 'Type content...' },
        { id: 'dh', label: 'D/H', visible: true, order: 5, placeholder: 'Drug history...' },
        { id: 'diagnosis', label: 'Δ', visible: true, order: 6, placeholder: 'Diagnosis...' }
    ]
};

export const DEFAULT_FOOTER_CONFIG: PrescriptionFooterConfig = {
    disclaimerText: 'নিয়ম মাফিক ঔষধ খাবেন। ডাক্তারের পরামর্শ ব্যতীত ঔষধ পরিবর্তন নিষেধ।',
    showCredits: true,
    creditsText: 'Generated by MediPos System',
    backgroundColor: '#ffffff',
    textColor: '#1f2937'
};
